export { default as Banner } from './Banner'
export { default as Info } from './Info'
export { default as Product } from './Product'
export { default as Faq } from './Faq'
export { default as Branding } from './Branding'