import "./globals.css";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google"

const generalSans = localFont({
  src: [
    {
      path: "../../public/fonts/GeneralSans-Regular.woff2",
      weight: "400",
      style: "normal"
    },
    {
      path: "../../public/fonts/GeneralSans-Semibold.woff2",
      weight: "600",
      style: "normal"
    },
    {
      path: "../../public/fonts/GeneralSans-Bold.woff2",
      weight: "700",
      style: "normal"
    },
  ],
  variable: "--font-general",
});

const montserrat = Montserrat({
  weight: '600',
  subsets: ['latin'],
  variable: '--font-montserrat'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`w-full h-full ${generalSans.variable}`}>{children}</body>
    </html>
  );
}
